### ISSUE TITLE
session secret error on npm run dev

### ISSUE THREAD

**Issue by cvoadmin** [AlexandroMtzG/remix-page-blocks#15]
Renaming .env.example to process.env does nothing  
```
Error: SESSION_SECRET must be set
    at Object.<anonymous> (/remix-page-blocks/app/utils/session.server.ts:10:9)
    
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /remix-page-blocks/node_modules/@remix-run/serve/dist/index.js:43:17
    at Layer.handle [as handle_request] (/remix-page-blocks/node_modules/express/lib/router/layer.js:95:5)
    at next (/remix-page-blocks/node_modules/express/lib/router/route.js:137:13)
    
```

**Comment by AlexandroMtzG** [comment]
@cvoadmin Try renaming `.env.example` to `.env` #16

**Comment by cvoadmin** [comment]
It works.

**Comment by cvoadmin** [comment]
BTW, what's your way of removing editor components, among other stuff, for production? 
Replaced everything after defaultLandingPage.ts:33. I like this workflow.

**Comment by AlexandroMtzG** [comment]
@cvoadmin I haven’t improved it since this release, but I’m already using it in production in 2 websites, saasrock.com and factura.so (you can toggle ?editMode=true in both of them)
